#!/bin/bash

echo "Een moment geduld A.U.B. uw silver webservers en loadbalancer worden aangemaakt"

# Vagrant maakt silver webservers en loadbalancer aan
vagrant up

# Ansible configureert de silver webservers en loadbalancer
ansible-playbook silver-config.yml


echo "Uw silvers servers zijn aangemaakt en gereed voor gebruik"


