---

# common
- hosts: webservers
  sudo: yes
  gather_facts: no

  tasks:

  - name: install git
    apt: name=git state=installed update_cache=yes

# web
- hosts: webservers
  sudo: yes

  tasks:
  
  - name: ensure apt cache is up to date
    apt: update_cache=yes
    
  - name: Install Php packages and postgresql client
    apt: name={{item}} state=latest update_cache=yes
    with_items:
        - php5-fpm
        - php5-pgsql
        - postgresql-client
    
  - name: install nginx 
    apt: name=nginx state=installed

  - name: write our nginx.conf
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify: restart nginx

  - name: write our /etc/nginx/sites-available/default
    template: src=templates/default-site.j2 dest=/etc/nginx/sites-available/default
    notify: restart nginx

  - name: deploy website content
    template: src=templates/index.php dest=/usr/share/nginx/html/index.php

  handlers:

  - name: restart nginx
    service: name=nginx state=restarted

# lb
- hosts: loadbalancers
  sudo: yes  

  tasks:

  - name: install haproxy and socat
    apt: pkg={{ item }} state=latest
    with_items:
    - haproxy
    - socat

  - name: enable haproxy
    lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
    notify: restart haproxy 

  - name: deploy haproxy config
    template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
    notify: restart haproxy

  handlers:

  - name: restart haproxy
    service: name=haproxy state=restarted
