#!/bin/bash

echo "Een moment geduld A.U.B. uw bronze webserver wordt aangemaakt"

# Vagrant maakt bronze webserver aan
vagrant up

# Ansible configureert de bronze webserver
ansible-playbook bronze-config.yml

echo "Uw bronze webserver is aangemaakt en gereed voor gebruik"

